// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lggoryptfxfuqtlkojsd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxnZ29yeXB0ZnhmdXF0bGtvanNkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkxMjg2NDEsImV4cCI6MjA3NDcwNDY0MX0.u7QrZqqt_on04qgKMr6DBDSjMvb4yYKvg4FnqFjLzqU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});